name: "Bug"
description: "Something is broken or not meeting acceptance criteria."
title: "[Bug] "
labels: ["bug","priority:high"]
body:
  - type: input
    id: env
    attributes:
      label: Environment (browser/device)
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      value: |
        1. 
        2. 
        3. 
  - type: textarea
    id: expected
    attributes:
      label: Expected result
  - type: textarea
    id: actual
    attributes:
      label: Actual result